{% set name = "janitor-rs" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/janitor_rs-{{ version }}.tar.gz
  sha256: 441b1a6f4c2a4d80010704a019147a2b689ca4c6bf325eaf82d9679ed5efc0f3

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.9,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.9,<2.0
    - pip
  run:
    - python

test:
  imports:
    - janitor_rs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyjanitor-devs/janitor-rs
  summary: Improve perf for pyjanitor functions with Rust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ericmjl
